# Generated by Django 4.2.23 on 2025-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_remove_transaction_user_transaction_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
