# Generated by Django 4.2.23 on 2025-08-29 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_alter_account_last_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
