# Generated by Django 4.2.23 on 2025-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_alter_account_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Finance App', max_length=100)),
                ('theme', models.JSONField(default=dict)),
                ('authentication', models.JSONField(default=dict)),
                ('income_tracking', models.JSONField(default=dict)),
            ],
        ),
    ]
