# Generated by Django 4.2.23 on 2025-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0006_usersetting_delete_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('rent', 'Rent'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=20),
        ),
    ]
