# Generated by Django 4.2.23 on 2025-09-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0010_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
