# Generated by Django 4.2.23 on 2025-09-01 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeapp', '0011_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='WealthyWise', max_length=100)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('default_theme', models.CharField(default='dark', max_length=20)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_auto_categorize', models.BooleanField(default=True)),
                ('enable_two_factor', models.BooleanField(default=False)),
                ('enable_email_alerts', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.RenameField(
            model_name='usersetting',
            old_name='auto_categorize',
            new_name='auto_categorize_enabled',
        ),
        migrations.RenameField(
            model_name='usersetting',
            old_name='email_alerts',
            new_name='email_alerts_enabled',
        ),
        migrations.RenameField(
            model_name='usersetting',
            old_name='notifications',
            new_name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='two_factor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_categorize_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='theme',
            field=models.CharField(default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
