# Generated by Django 4.2.23 on 2025-09-02 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0012_appsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
