# Generated by Django 4.2.23 on 2025-09-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='avatar',
        ),
    ]
