# Generated by Django 4.2.23 on 2025-09-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0018_alter_account_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.FloatField(default=0.0),
        ),
    ]
