# Generated by Django 4.2.23 on 2025-09-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0021_alter_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
