# Generated by Django 4.2.23 on 2025-09-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0023_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
