# Generated by Django 4.2.23 on 2025-09-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0025_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('dividend', 'Dividend'), ('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('rent', 'Rent'), ('mortgage', 'Mortgage'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('insurance', 'Insurance'), ('gift', 'Gift'), ('other', 'Other')], max_length=50),
        ),
    ]
