# Generated by Django 4.2.23 on 2025-09-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0026_alter_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('dividend', 'Dividend'), ('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('rent', 'Rent'), ('mortgage', 'Mortgage'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('insurance', 'Insurance'), ('gift', 'Gift'), ('other', 'Other')], max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='budget_category', to='financeapp.transaction'),
        ),
    ]
